import { z } from "zod";

export const carSchema = z.object({
  slug: z.string().min(3).max(120).regex(/^[a-z0-9-]+$/),
  brand: z.string().min(1).max(50),
  model: z.string().min(1).max(80),
  year: z.coerce.number().int().min(1980).max(2030),
  priceUSD: z.coerce.number().int().min(500).max(2_000_000),
  negotiable: z.coerce.boolean().optional(),
  mileage: z.coerce.number().int().min(0).optional(),
  transmission: z.string().max(50).optional(),
  fuel: z.string().max(30).optional(),
  bodyType: z.string().max(30).optional(),
  condition: z.string().max(30).optional(),
  colorName: z.string().max(40).optional(),
  colorHex: z.string().max(10).optional(),
  engine: z.string().max(60).optional(),
  cylinders: z.coerce.number().int().min(0).max(16).optional(),
  horsepower: z.coerce.number().int().min(0).max(3000).optional(),
  torque: z.coerce.number().int().min(0).max(5000).optional(),
  acceleration: z.coerce.number().min(0).max(60).optional(),
  drivetrain: z.string().max(30).optional(),
  seats: z.coerce.number().int().min(1).max(20).optional(),
  doors: z.coerce.number().int().min(2).max(6).optional(),
  fuelEconomy: z.string().max(40).optional(),
  lengthMm: z.coerce.number().int().min(0).optional(),
  widthMm: z.coerce.number().int().min(0).optional(),
  heightMm: z.coerce.number().int().min(0).optional(),
  weightKg: z.coerce.number().int().min(0).optional(),
  safety: z.string().optional(),
  comfort: z.string().optional(),
  exterior: z.string().optional(),
  images: z.string().optional(),
  description: z.string().max(4000).optional(),
  vin: z.string().max(30).optional().nullable(),
  inspection: z.string().max(300).optional(),
  warranty: z.string().max(200).optional(),
  featured: z.coerce.boolean().optional(),
  sold: z.coerce.boolean().optional(),
});

export const jobSchema = z.object({
  title: z.string().min(2).max(80),
  category: z.string().min(2).max(40),
  location: z.string().min(2).max(100),
  salary: z.string().max(80).optional().or(z.literal("")),
  hours: z.string().max(80).optional().or(z.literal("")),
  description: z.string().max(1000).optional().or(z.literal("")),
  employerName: z.string().min(2).max(80),
  employerPhone: z.string().min(7).max(20),
  employerAddress: z.string().max(160).optional().or(z.literal("")),
  active: z.coerce.boolean().optional(),
});
